//! Matter TLV encoders and decoders for Ambient Context Sensing Cluster
//! Cluster IDs: 0x0431
//!
//! This file is automatically generated from AmbientContextSensing.xml

#![allow(clippy::too_many_arguments)]

use crate::tlv;
use anyhow;
use serde_json;


// Struct definitions

#[derive(Debug, serde::Serialize)]
pub struct AmbientContextType {

}

#[derive(Debug, serde::Serialize)]
pub struct HoldTimeLimits {
    pub hold_time_min: Option<u16>,
    pub hold_time_max: Option<u16>,
    pub hold_time_default: Option<u16>,
}

#[derive(Debug, serde::Serialize)]
pub struct ObjectCountConfig {
    pub object_count_threshold: Option<u16>,
}

#[derive(Debug, serde::Serialize)]
pub struct PredictedActivity {
    pub start_timestamp: Option<u64>,
    pub end_timestamp: Option<u64>,
    pub crowd_detected: Option<bool>,
    pub crowd_count: Option<u8>,
    pub confidence: Option<u8>,
}

// Attribute decoders

/// Decode HumanActivityDetected attribute (0x0000)
pub fn decode_human_activity_detected(inp: &tlv::TlvItemValue) -> anyhow::Result<bool> {
    if let tlv::TlvItemValue::Bool(v) = inp {
        Ok(*v)
    } else {
        Err(anyhow::anyhow!("Expected Bool"))
    }
}

/// Decode ObjectIdentified attribute (0x0001)
pub fn decode_object_identified(inp: &tlv::TlvItemValue) -> anyhow::Result<bool> {
    if let tlv::TlvItemValue::Bool(v) = inp {
        Ok(*v)
    } else {
        Err(anyhow::anyhow!("Expected Bool"))
    }
}

/// Decode AudioContextDetected attribute (0x0002)
pub fn decode_audio_context_detected(inp: &tlv::TlvItemValue) -> anyhow::Result<bool> {
    if let tlv::TlvItemValue::Bool(v) = inp {
        Ok(*v)
    } else {
        Err(anyhow::anyhow!("Expected Bool"))
    }
}

/// Decode AmbientContextType attribute (0x0003)
pub fn decode_ambient_context_type(inp: &tlv::TlvItemValue) -> anyhow::Result<Vec<AmbientContextType>> {
    let mut res = Vec::new();
    if let tlv::TlvItemValue::List(v) = inp {
        for _item in v {
            res.push(AmbientContextType {

            });
        }
    }
    Ok(res)
}

/// Decode AmbientContextTypeSupported attribute (0x0004)
pub fn decode_ambient_context_type_supported(inp: &tlv::TlvItemValue) -> anyhow::Result<Vec<u8>> {
    let mut res = Vec::new();
    if let tlv::TlvItemValue::List(v) = inp {
        for item in v {
            if let tlv::TlvItemValue::Int(i) = &item.value {
                res.push(*i as u8);
            }
        }
    }
    Ok(res)
}

/// Decode ObjectCountReached attribute (0x0005)
pub fn decode_object_count_reached(inp: &tlv::TlvItemValue) -> anyhow::Result<bool> {
    if let tlv::TlvItemValue::Bool(v) = inp {
        Ok(*v)
    } else {
        Err(anyhow::anyhow!("Expected Bool"))
    }
}

/// Decode ObjectCountConfig attribute (0x0006)
pub fn decode_object_count_config(inp: &tlv::TlvItemValue) -> anyhow::Result<ObjectCountConfig> {
    if let tlv::TlvItemValue::List(_fields) = inp {
        // Struct with fields
        let item = tlv::TlvItem { tag: 0, value: inp.clone() };
        Ok(ObjectCountConfig {
                object_count_threshold: item.get_int(&[1]).map(|v| v as u16),
        })
    } else {
        Err(anyhow::anyhow!("Expected struct fields"))
    }
}

/// Decode ObjectCount attribute (0x0007)
pub fn decode_object_count(inp: &tlv::TlvItemValue) -> anyhow::Result<u16> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(*v as u16)
    } else {
        Err(anyhow::anyhow!("Expected UInt16"))
    }
}

/// Decode SimultaneousDetectionLimit attribute (0x0008)
pub fn decode_simultaneous_detection_limit(inp: &tlv::TlvItemValue) -> anyhow::Result<u8> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(*v as u8)
    } else {
        Err(anyhow::anyhow!("Expected UInt8"))
    }
}

/// Decode HoldTime attribute (0x0009)
pub fn decode_hold_time(inp: &tlv::TlvItemValue) -> anyhow::Result<u16> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(*v as u16)
    } else {
        Err(anyhow::anyhow!("Expected UInt16"))
    }
}

/// Decode HoldTimeLimits attribute (0x000A)
pub fn decode_hold_time_limits(inp: &tlv::TlvItemValue) -> anyhow::Result<HoldTimeLimits> {
    if let tlv::TlvItemValue::List(_fields) = inp {
        // Struct with fields
        let item = tlv::TlvItem { tag: 0, value: inp.clone() };
        Ok(HoldTimeLimits {
                hold_time_min: item.get_int(&[0]).map(|v| v as u16),
                hold_time_max: item.get_int(&[1]).map(|v| v as u16),
                hold_time_default: item.get_int(&[2]).map(|v| v as u16),
        })
    } else {
        Err(anyhow::anyhow!("Expected struct fields"))
    }
}

/// Decode PredictedActivity attribute (0x000B)
pub fn decode_predicted_activity(inp: &tlv::TlvItemValue) -> anyhow::Result<Vec<PredictedActivity>> {
    let mut res = Vec::new();
    if let tlv::TlvItemValue::List(v) = inp {
        for item in v {
            res.push(PredictedActivity {
                start_timestamp: item.get_int(&[0]),
                end_timestamp: item.get_int(&[1]),
                crowd_detected: item.get_bool(&[3]),
                crowd_count: item.get_int(&[4]).map(|v| v as u8),
                confidence: item.get_int(&[5]).map(|v| v as u8),
            });
        }
    }
    Ok(res)
}


// JSON dispatcher function

/// Decode attribute value and return as JSON string
///
/// # Parameters
/// * `cluster_id` - The cluster identifier
/// * `attribute_id` - The attribute identifier
/// * `tlv_value` - The TLV value to decode
///
/// # Returns
/// JSON string representation of the decoded value or error
pub fn decode_attribute_json(cluster_id: u32, attribute_id: u32, tlv_value: &crate::tlv::TlvItemValue) -> String {
    // Verify this is the correct cluster
    if ![0x0431].contains(&cluster_id) {
        return format!("{{\"error\": \"Invalid cluster ID. Expected [0x0431], got {}\"}}", cluster_id);
    }

    match attribute_id {
        0x0000 => {
            match decode_human_activity_detected(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0001 => {
            match decode_object_identified(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0002 => {
            match decode_audio_context_detected(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0003 => {
            match decode_ambient_context_type(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0004 => {
            match decode_ambient_context_type_supported(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0005 => {
            match decode_object_count_reached(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0006 => {
            match decode_object_count_config(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0007 => {
            match decode_object_count(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0008 => {
            match decode_simultaneous_detection_limit(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0009 => {
            match decode_hold_time(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x000A => {
            match decode_hold_time_limits(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x000B => {
            match decode_predicted_activity(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        _ => format!("{{\"error\": \"Unknown attribute ID: {}\"}}", attribute_id),
    }
}

/// Get list of all attributes supported by this cluster
///
/// # Returns
/// Vector of tuples containing (attribute_id, attribute_name)
pub fn get_attribute_list() -> Vec<(u32, &'static str)> {
    vec![
        (0x0000, "HumanActivityDetected"),
        (0x0001, "ObjectIdentified"),
        (0x0002, "AudioContextDetected"),
        (0x0003, "AmbientContextType"),
        (0x0004, "AmbientContextTypeSupported"),
        (0x0005, "ObjectCountReached"),
        (0x0006, "ObjectCountConfig"),
        (0x0007, "ObjectCount"),
        (0x0008, "SimultaneousDetectionLimit"),
        (0x0009, "HoldTime"),
        (0x000A, "HoldTimeLimits"),
        (0x000B, "PredictedActivity"),
    ]
}

// Typed facade (invokes + reads)

/// Read `HumanActivityDetected` attribute from cluster `Ambient Context Sensing`.
pub async fn read_human_activity_detected(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<bool> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_AMBIENT_CONTEXT_SENSING, crate::clusters::defs::CLUSTER_AMBIENT_CONTEXT_SENSING_ATTR_ID_HUMANACTIVITYDETECTED).await?;
    decode_human_activity_detected(&tlv)
}

/// Read `ObjectIdentified` attribute from cluster `Ambient Context Sensing`.
pub async fn read_object_identified(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<bool> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_AMBIENT_CONTEXT_SENSING, crate::clusters::defs::CLUSTER_AMBIENT_CONTEXT_SENSING_ATTR_ID_OBJECTIDENTIFIED).await?;
    decode_object_identified(&tlv)
}

/// Read `AudioContextDetected` attribute from cluster `Ambient Context Sensing`.
pub async fn read_audio_context_detected(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<bool> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_AMBIENT_CONTEXT_SENSING, crate::clusters::defs::CLUSTER_AMBIENT_CONTEXT_SENSING_ATTR_ID_AUDIOCONTEXTDETECTED).await?;
    decode_audio_context_detected(&tlv)
}

/// Read `AmbientContextType` attribute from cluster `Ambient Context Sensing`.
pub async fn read_ambient_context_type(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<Vec<AmbientContextType>> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_AMBIENT_CONTEXT_SENSING, crate::clusters::defs::CLUSTER_AMBIENT_CONTEXT_SENSING_ATTR_ID_AMBIENTCONTEXTTYPE).await?;
    decode_ambient_context_type(&tlv)
}

/// Read `AmbientContextTypeSupported` attribute from cluster `Ambient Context Sensing`.
pub async fn read_ambient_context_type_supported(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<Vec<u8>> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_AMBIENT_CONTEXT_SENSING, crate::clusters::defs::CLUSTER_AMBIENT_CONTEXT_SENSING_ATTR_ID_AMBIENTCONTEXTTYPESUPPORTED).await?;
    decode_ambient_context_type_supported(&tlv)
}

/// Read `ObjectCountReached` attribute from cluster `Ambient Context Sensing`.
pub async fn read_object_count_reached(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<bool> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_AMBIENT_CONTEXT_SENSING, crate::clusters::defs::CLUSTER_AMBIENT_CONTEXT_SENSING_ATTR_ID_OBJECTCOUNTREACHED).await?;
    decode_object_count_reached(&tlv)
}

/// Read `ObjectCountConfig` attribute from cluster `Ambient Context Sensing`.
pub async fn read_object_count_config(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<ObjectCountConfig> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_AMBIENT_CONTEXT_SENSING, crate::clusters::defs::CLUSTER_AMBIENT_CONTEXT_SENSING_ATTR_ID_OBJECTCOUNTCONFIG).await?;
    decode_object_count_config(&tlv)
}

/// Read `ObjectCount` attribute from cluster `Ambient Context Sensing`.
pub async fn read_object_count(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<u16> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_AMBIENT_CONTEXT_SENSING, crate::clusters::defs::CLUSTER_AMBIENT_CONTEXT_SENSING_ATTR_ID_OBJECTCOUNT).await?;
    decode_object_count(&tlv)
}

/// Read `SimultaneousDetectionLimit` attribute from cluster `Ambient Context Sensing`.
pub async fn read_simultaneous_detection_limit(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<u8> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_AMBIENT_CONTEXT_SENSING, crate::clusters::defs::CLUSTER_AMBIENT_CONTEXT_SENSING_ATTR_ID_SIMULTANEOUSDETECTIONLIMIT).await?;
    decode_simultaneous_detection_limit(&tlv)
}

/// Read `HoldTime` attribute from cluster `Ambient Context Sensing`.
pub async fn read_hold_time(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<u16> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_AMBIENT_CONTEXT_SENSING, crate::clusters::defs::CLUSTER_AMBIENT_CONTEXT_SENSING_ATTR_ID_HOLDTIME).await?;
    decode_hold_time(&tlv)
}

/// Read `HoldTimeLimits` attribute from cluster `Ambient Context Sensing`.
pub async fn read_hold_time_limits(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<HoldTimeLimits> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_AMBIENT_CONTEXT_SENSING, crate::clusters::defs::CLUSTER_AMBIENT_CONTEXT_SENSING_ATTR_ID_HOLDTIMELIMITS).await?;
    decode_hold_time_limits(&tlv)
}

/// Read `PredictedActivity` attribute from cluster `Ambient Context Sensing`.
pub async fn read_predicted_activity(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<Vec<PredictedActivity>> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_AMBIENT_CONTEXT_SENSING, crate::clusters::defs::CLUSTER_AMBIENT_CONTEXT_SENSING_ATTR_ID_PREDICTEDACTIVITY).await?;
    decode_predicted_activity(&tlv)
}

#[derive(Debug, serde::Serialize)]
pub struct AmbientContextDetectStartedEvent {
    pub ambient_context_detected: Option<AmbientContextType>,
    pub object_count_reached: Option<bool>,
    pub object_count: Option<u16>,
}

#[derive(Debug, serde::Serialize)]
pub struct AmbientContextDetectEndedEvent {
    pub event_start_time: Option<u8>,
}

// Event decoders

/// Decode AmbientContextDetectStarted event (0x00, priority: info)
pub fn decode_ambient_context_detect_started_event(inp: &tlv::TlvItemValue) -> anyhow::Result<AmbientContextDetectStartedEvent> {
    if let tlv::TlvItemValue::List(_fields) = inp {
        let item = tlv::TlvItem { tag: 0, value: inp.clone() };
        Ok(AmbientContextDetectStartedEvent {
                                ambient_context_detected: {
                    if let Some(nested_tlv) = item.get(&[0]) {
                        if let tlv::TlvItemValue::List(_) = nested_tlv {
                            let _nested_item = tlv::TlvItem { tag: 0, value: nested_tlv.clone() };
                            Some(AmbientContextType {

                            })
                        } else {
                            None
                        }
                    } else {
                        None
                    }
                },
                                object_count_reached: item.get_bool(&[1]),
                                object_count: item.get_int(&[2]).map(|v| v as u16),
        })
    } else {
        Err(anyhow::anyhow!("Expected struct fields"))
    }
}

/// Decode AmbientContextDetectEnded event (0x01, priority: info)
pub fn decode_ambient_context_detect_ended_event(inp: &tlv::TlvItemValue) -> anyhow::Result<AmbientContextDetectEndedEvent> {
    if let tlv::TlvItemValue::List(_fields) = inp {
        let item = tlv::TlvItem { tag: 0, value: inp.clone() };
        Ok(AmbientContextDetectEndedEvent {
                                event_start_time: item.get_int(&[0]).map(|v| v as u8),
        })
    } else {
        Err(anyhow::anyhow!("Expected struct fields"))
    }
}


// Event JSON dispatcher

/// Decode event value and return as JSON string
pub fn decode_event_json(cluster_id: u32, event_id: u32, tlv_value: &crate::tlv::TlvItemValue) -> String {
    if ![0x0431].contains(&cluster_id) {
        return format!("{{\"error\": \"Invalid cluster ID. Expected [0x0431], got {}\"}}", cluster_id);
    }

    match event_id {
        0x00 => {
            match decode_ambient_context_detect_started_event(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x01 => {
            match decode_ambient_context_detect_ended_event(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        _ => format!("{{\"error\": \"Unknown event ID: {}\"}}", event_id),
    }
}

/// Get list of all events supported by this cluster
///
/// # Returns
/// Vector of tuples containing (event_id, event_name)
pub fn get_event_list() -> Vec<(u32, &'static str)> {
    vec![
        (0x00, "AmbientContextDetectStarted"),
        (0x01, "AmbientContextDetectEnded"),
    ]
}

